name: 'Qualys Container Scan'
description: 'Run Qualys QScanner on a container image and output results'
inputs:
  image-name:
    description: 'Container image to scan'
    required: true
  qscanner-version:
    description: 'QScanner CLI version to install'
    required: false
    default: 'latest'
  config-url:
    description: 'URL to download QScanner config.json'
    required: false
    default: 'https://example.com/qscanner/config/config.json'

runs:
  using: "composite"
  steps:
    - name: Install QScanner CLI
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/install-qscanner.sh
        ${{ github.action_path }}/scripts/install-qscanner.sh "${{ inputs.qscanner-version }}"

    - name: Download Qualys configuration
      shell: bash
      run: |
        curl -sSL "${{ inputs.config-url }}" -o config.json