name: Trigger CodeQL Validation

on:
  workflow_run:
    workflows: ["CodeQL Analysis"]
    types:
      - completed

permissions:
  contents: write

jobs:
  validate-codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CodeQL Results
        uses: actions/download-artifact@v4
        with:
          name: codeql-results
          path: ./results

      - name: Validate CodeQL from External Action
        uses: mroluyomiosh/Qualys/.github/actions/codeql@main
        with:
          github_token: ${{ secrets.API_ACCESS_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.sha }}
